---

- name: Configure necessary software in EC2
  hosts: jenkins
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install necessary software
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3-pip
        - python3-venv
        - awscli
        - openjdk-17-jdk
        - openjdk-17-jre
        - gnupg
        - software-properties-common
        - unzip
        - ansible
        - docker.io
        - docker-buildx
        - git

    - name: Install boto3
      pip:
        name: boto3
        state: present

    - name: Download Terraform Binary
      unarchive:
        src: "https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip"
        dest: /usr/bin
        remote_src: True

    - name: Add Jenkins repo key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repo
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Add ubuntu/jenkins user to docker group
      user:
        name: "{{item}}"
        groups: docker
        append: yes
        state: present
      loop:
        - ubuntu
        - jenkins

    - name: Reboot the remote EC2 machine
      reboot:

    - name: ensure that the known_host fle is present
      file:
        path: /root/.ssh/known_hosts
        owner: root
        state: touch

    - name: ensure that the jenkins ssh folder is present
      file:
        path: /var/lib/jenkins/.ssh
        owner: jenkins
        state: directory
        recurse: true

    - name: copy user's key to remote machine
      copy:
        src: /home/ubuntu/.ssh/id_rsa
        dest: "{{item.value}}"
        owner: "{{item.key}}"
        mode: '0400'
      loop: "{{ data | dict2items}}"
      vars:
        data:
          root: /root/.ssh/id_rsa
          jenkins: /var/lib/jenkins/.ssh/id_rsa
          ubuntu: /home/ubuntu/.ssh/id_rsa

    - name: add key to known_hosts file
      shell: "ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts"

    - name: copy known_hosts to remote machine
      copy:
        src: /root/.ssh/known_hosts
        dest: /var/lib/jenkins/.ssh/known_hosts
        owner: jenkins
        mode: '0644'
        remote_src: true

    - name: Clone the StaycationX repository
      git:
        repo: 'git@github.com:USERNAME/staycationX.git'
        dest: /opt/staycationX
        version: nginx

    - name: Download docker compose
      get_url:
        url : "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"

    - name: Run docker compose
      command: docker-compose -f /opt/staycationX/dockerhub.yml up -d
      