---

- name: Configure necessary software in EC2
  hosts: jenkins
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install necessary software
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - python3-pip
        - python3-venv
        - awscli
        - openjdk-17-jdk
        - openjdk-17-jre
        - gnupg
        - software-properties-common
        - unzip
        - ansible
        - docker.io
        - docker-buildx

    - name: Install boto3
      pip:
        name: boto3
        state: present

    - name: Download Terraform Binary
      unarchive:
        src: "https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip"
        dest: /usr/bin
        remote_src: True

    - name: Add Jenkins repo key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repo
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Add ubuntu/jenkins user to docker group
      user:
        name: "{{item}}"
        groups: docker
        append: yes
        state: present
      loop:
        - ubuntu
        - jenkins