---

- name: Run docker containers
  hosts: tag_group_web
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Install necessary software
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker.io

    - name: Install docker compose
      get_url:
        url : "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes
  
    - name: ensure that the known_hosts file is present
      file:
        path: /root/.ssh/known_hosts
        owner: root
        state: touch

    - name: copy user's key to remote machine
      copy:
        src: /var/lib/jenkins/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        mode: '0400'

    - name: add key to known_hosts file
      shell: "ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts"

    - name: Git checkout dockerhub.yml from repo
      git:
        repo: 'git@github.com:USERNAME/staycationX.git'
        dest: /opt/staycationX
        version: nginx

    - name: Stop running containers.
      command: docker-compose down
      args:
        chdir: /opt/staycationX
    
    - name: Remove all images
      shell: docker rmi -f $(docker images -a -q)
      ignore_errors: true

    - name: Run docker compose
      command: docker-compose -f /opt/staycationX/dockerhub.yml up -d