---

- name: Run application with docker containers on deployment server
  hosts: tag_group_web
  gather_facts: false
  become: yes
  become_user: root
  become_method: sudo
  vars:
    jenkins_path: /var/lib/jenkins/workspace/
    pipeline_name: pipeline1

  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt cache and install docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Copy dockerhub.yml from delivery machine to deployment machine
      copy:
        src: "{{jenkins_path}}/{{pipeline_name}}/StaycationX/dockerhub.yml"
        dest: /root/dockerhub.yml
        owner: root
        group: root
        mode: '0644'

    - name: Stop running containers
      command: docker compose -f dockerhub.yml down
      args:
        chdir: /root
    
    - name: Remove all images
      shell: docker rmi -f $(sudo docker images -a -q)
      ignore_errors: true

    - name: Run docker compose
      command: docker compose -f /root/dockerhub.yml up -d